x-superset-user: &superset-user root
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./superset:/app/superset
  - ./superset-core:/app/superset-core
  - ./superset-frontend:/app/superset-frontend
  - superset_data:/app/data


services:
  db:
    container_name: postgres-container
    image: postgres:14.17
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network
  af:
    container_name: airflow-container
    image: apache/airflow:3.0.0
    ports:
      - 8000:8080
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./api-requests:/opt/airflow/api-requests
    depends_on:
      - db
    networks:
      - my_network
    command: >
      bash -c "airflow db migrate && airflow standalone"

  dbt:
    container_name: dbt-container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    volumes:
      - ./dbt/my_project:/usr/app
      - ./dbt:/root/.dbt
      - ./var/run/docker.sock:/var/run/docker.sock
    group_add:
      - '1001'
    working_dir: /usr/app
    environment:
      DBT_PROFILES_DIR: "/root/.dbt"
    depends_on:
      - db
    networks:
      - my_network
    command:
      run
  superset:
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    image: apache/superset:3.0.0
    command: [ "/app/docker/docker-bootstrap.sh", "app" ]
    restart: unless-stopped
    ports:
      - ${SUPERSET_PORT:-8088}:8088
      # When in cypress-mode ->
      - ${CYPRESS_PORT:-8081}:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: *superset-user
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes

  superset-websocket:
    build: ./superset-websocket
    ports:
      - ${WEBSOCKET_PORT:-8080}:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    # Mount everything in superset-websocket into container and
    # then exclude node_modules and dist with bogus volume mount.
    # This is necessary because host and container need to have
    # their own, separate versions of these files. .dockerignore
    # does not seem to work when starting the service through
    # docker compose.
    #
    # For example, node_modules may contain libs with native bindings.
    # Those bindings need to be compiled for each OS and the container
    # OS is not necessarily the same as host OS.
    volumes:
      - ./superset-websocket:/home/superset-websocket
      - /home/superset-websocket/node_modules
      - /home/superset-websocket/dist

      # Mount config file. Create your own docker/superset-websocket/config.json
      # for custom settings, then point to it here. Do not use this example in production.
      - ./docker/superset-websocket/config.example.json:/home/superset-websocket/config.json:ro
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SSL=false
  superset-init:
    image: apache/superset:3.0.0
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    user: *superset-user
    volumes: *superset-volumes
    healthcheck:
      disable: true
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
networks:
  my_network:
    driver: bridge